import 'package:flutter/material.dart';

import '../config/app_config.dart';

/// Branded launch screen, shown briefly before the auth gate resolves.
///
/// Deliberately dumber than customer_app's equivalent. That one reads AuthState
/// and pushes Home or Login itself; this one pushes [next] and lets the caller's
/// existing gate decide. Keeping the decision where it already lives means the
/// owner-side routing rule has exactly one implementation — this screen cannot
/// drift out of step with it, and adding the splash changed no auth behaviour.
///
/// It also covers a real gap rather than only decorating one. `AuthState`
/// starts `loggedIn == false` and flips it inside an async `bootstrap()`, so
/// before this screen existed an already-signed-in owner could see LoginScreen
/// flash before Home replaced it. The pause here normally outlasts that
/// SharedPreferences read — normally, not guaranteed: it is a timing overlap,
/// not a barrier, and a genuine fix would be a `bootstrapped` flag on AuthState.
class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key, required this.next});

  /// Built after the pause. This is the app's real routing gate.
  final WidgetBuilder next;

  /// The brand lockup, keyed onto transparency so it sits on the tinted field
  /// without a white slab behind it. Generated by scripts/make_app_icon.py —
  /// byte-identical to the file customer_app ships.
  static const String logoAsset = 'assets/brand/gusto_logo.png';

  /// Lets tests assert the logo renders without matching on a text string the
  /// logo itself carries as artwork.
  static const Key logoKey = Key('splash_logo');

  /// Matches `@color/gusto_splash` and `scaffoldBackgroundColor`, so the native
  /// launch window, this screen and the screen after it are one flat surface.
  static const Color background = Color(0xFFF7F6F9);

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  void initState() {
    super.initState();
    _boot();
  }

  Future<void> _boot() async {
    await Future<void>.delayed(const Duration(milliseconds: 900));
    if (!mounted) return;
    Navigator.of(context).pushReplacement(
      MaterialPageRoute(builder: widget.next),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: SplashScreen.background,
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 48),
              child: Image.asset(
                SplashScreen.logoAsset,
                key: SplashScreen.logoKey,
                // The stacked mark is 1.49:1. Width-bound rather than a fixed
                // height, so it scales with the device instead of overflowing
                // narrow screens.
                fit: BoxFit.contain,
                semanticLabel: AppConfig.appName,
              ),
            ),
            const SizedBox(height: 18),
            // The lockup reads "Gusto Skip" — the CUSTOMER product. This label
            // is what tells the person holding a tablet that they opened the
            // staff app instead. It sits where customer_app puts its
            // "SKIP THE LINE" tagline, so the two screens still rhyme.
            Text(
              'OWNER',
              style: Theme.of(context).textTheme.titleMedium?.copyWith(
                    color: const Color(AppConfig.brandInk),
                    fontWeight: FontWeight.w700,
                    letterSpacing: 6,
                  ),
            ),
            const SizedBox(height: 40),
            const SizedBox(
              width: 28,
              height: 28,
              child: CircularProgressIndicator(
                color: Color(AppConfig.brandPurple),
                strokeWidth: 3,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
