import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

import '../config/app_config.dart';
import '../state/auth_state.dart';
import '../theme/app_colors.dart';
import 'home_screen.dart';
import 'login_screen.dart';

/// Splash / theme-init gate. Decides the entry screen based on session.
class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  /// The brand lockup, keyed onto transparency so it sits on the cream field
  /// without a white slab behind it. Generated by scripts/make_app_icon.py.
  static const String logoAsset = 'assets/brand/gusto_logo.png';

  /// Lets tests assert the logo renders without matching on a text string the
  /// logo itself now carries as artwork.
  static const Key logoKey = Key('splash_logo');

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> {
  @override
  void initState() {
    super.initState();
    _boot();
  }

  Future<void> _boot() async {
    // Brief branded pause; theme + token are already loaded in main().
    await Future<void>.delayed(const Duration(milliseconds: 900));
    if (!mounted) return;
    final authed = context.read<AuthState>().isAuthenticated;
    Navigator.of(context).pushReplacement(
      MaterialPageRoute(
        builder: (_) => authed ? const HomeScreen() : const LoginScreen(),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final c = AppColors.of(context);
    return Scaffold(
      // Cream, not purple. AppColors.cream (#F6EFE2) is the app's already-
      // defined warm tone — no new hex invented. The Android launch window is
      // painted the same colour (@color/carevo_splash), so the native splash
      // and this screen are one continuous surface rather than a cream flash
      // followed by a purple one.
      backgroundColor: AppColors.cream,
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // The brand lockup, not a typeset wordmark. It already reads
            // "Gusto Skip" and carries the spork, so the neobrutalist accent
            // card that used to hold the word is gone with it — boxing a logo
            // that has its own whitespace only crops it visually.
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 40),
              child: Image.asset(
                SplashScreen.logoAsset,
                key: SplashScreen.logoKey,
                // The mark is 2.32:1; width-bound so it scales with the device
                // rather than a fixed height that overflows narrow screens.
                fit: BoxFit.contain,
                semanticLabel: AppConfig.appName,
              ),
            ),
            const SizedBox(height: 18),
            // Ink, not onPrimary. onPrimary is white — correct on the old
            // purple field, invisible on cream.
            Text(
              'SKIP THE LINE',
              style: GoogleFonts.spaceGrotesk(
                color: c.ink,
                fontSize: 16,
                fontWeight: FontWeight.w700,
                letterSpacing: 4,
              ),
            ),
            const SizedBox(height: 40),
            SizedBox(
              width: 28,
              height: 28,
              child: CircularProgressIndicator(color: c.ink, strokeWidth: 3),
            ),
            // The small AppConfig.appName footer that used to sit here is gone:
            // the lockup above now spells "Gusto Skip" as artwork, and printing
            // the same words again 40px below read as a duplicate rather than a
            // signature. The name still reaches screen readers via the image's
            // semanticLabel.
          ],
        ),
      ),
    );
  }
}
